.gitlab-ci.yml
scripts/ci/pre_cache.sh

Identical to https://github.com/paritytech/canvas/blob/master/.gitlab-ci.yml except `c/canvas/substrate-contracts-node`
@cmichi please review, add what's needed there.
btw: are you OK with having `main` as a default branch here? I'm mirroring it to `master` to avoid confusion.

CI: copypasta from canvas

---

runtime/src/lib.rs

I'll create a follow-up issue so that we don't forget removing it again.

Revert me: Temporarily allow large contracts

---

Cargo.lock
README.md

Follow-up to https://github.com/paritytech/substrate/pull/10366.

Sync with Substrate

---

Cargo.lock
README.md
node/Cargo.toml
runtime/Cargo.toml

Follow-up to https://github.com/paritytech/substrate/pull/10971.

Synchronize with Substrate + Release 0.8.0

---

Cargo.lock
node/src/cli.rs
node/src/command.rs
runtime/src/lib.rs

Hello a quick PR to fix Benchmark & LengthToFee
Also fix [#48](https://github.com/paritytech/substrate-contracts-node/issues/48)

Fixed Benchmark in command & LengthToFee

---

README.md

point to new location of contracts chain.

update now broken link

---

Cargo.lock
README.md
node/Cargo.toml
node/src/rpc.rs
runtime/Cargo.toml
runtime/src/lib.rs

The `seal_ecdsa_*` functions have been stabilized.

Sync with Substrate 2022-05-20

---

node/src/rpc.rs

Allows calling `dev_getBlockStats`, used e.g. by `povstats`

Register dev RPC api for block stats

---

README.md

[Preview here](https://github.com/paritytech/substrate-contracts-node/tree/cmichi-how-to-sync#how-to-synchronize-with-substrate).

Add guide for synchronizing with Substrate

---

.gitlab-ci.yml

related to https://github.com/paritytech/scripts/pull/444

[ci] fix main branch name

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml

Release `v0.19.0`

---

.gitlab-ci.yml

Fixes the failing ink! master CI: https://github.com/paritytech/ink/actions/runs/3248481958/jobs/5329744600.

Always produce Mac artifacts

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml

We just update the lock file and make a new release in order to include:
https://github.com/paritytech/substrate/pull/12677

Bump substrate

---

Cargo.lock
README.md
node/Cargo.toml
node/src/cli.rs
runtime/Cargo.toml
runtime/src/lib.rs

Sync the repository with Substrate's [`polkadot-v0.9.34`](https://github.com/paritytech/substrate/tree/polkadot-v0.9.34) branch.

Update to polkadot-v0.9.34 branch

---

Cargo.lock
README.md
node/Cargo.toml
runtime/Cargo.toml
runtime/build.rs
runtime/src/lib.rs

Sync the repository with Substrate's [polkadot-v0.9.37](https://github.com/paritytech/substrate/tree/polkadot-v0.9.37) branch.

Sync substrate

---

Cargo.lock
README.md
node/Cargo.toml
node/src/service.rs
runtime/Cargo.toml
runtime/src/lib.rs

Required for https://github.com/paritytech/ink/pull/1795 and https://github.com/paritytech/cargo-contract/pull/1149

Sync with `polkadot-v0.9.43` branch

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml

Sync with `polkadot-v1.0.0` in order to include https://github.com/paritytech/substrate/pull/14642.
Fixes #200

Release `v0.30.0`

---

node/Cargo.toml

Add back the version here this is required for deployment

set version

---

.gitlab-ci.yml
Cargo.lock
Cargo.toml
node/Cargo.toml
runtime/src/contracts_config.rs

Release 0.39.0

---

.github/workflows/ci.yml

Small fix for https://github.com/paritytech/substrate-contracts-node/pull/235

Add tag trigger to ci
