paritytech/substrate-contracts-node

Cargo.lock, README.md, runtime/Cargo.toml, runtime/src/lib.rs
This reverts commit 8d91b8e578065a7c06433cbd41ac059bf478a0bd.
We have to revert to the `Cargo.lock` from before the Metadata update. This is because the UI's don't yet support it.
=> Revert "Sync with Substrate (#6)"

Cargo.lock, README.md
Fixes the failing build with the latest Rust nightlies in our CI's. The fix was just now merged into Substrate.
=> Sync with Substrate

Cargo.lock, README.md, node/Cargo.toml, node/src/cli.rs, runtime/Cargo.toml, runtime/src/lib.rs
* Bump all dependencies including substrate (we got yanked errors when build `--locked`)
* Remove unused `MICROUNIT` (was generating warnings)
* Bump own version
=> Sync with substrate and bump version

node/Cargo.toml, node/src/chain_spec.rs, node/src/service.rs, runtime/Cargo.toml, runtime/src/lib.rs
Hello,
I've changed consensus from `aura` & `grandpa` with 6 seconds block-time.
To `manual-seal` where blocks are authored at every transaction.
It makes transactions almost instant and is very practical for hacking & testing
=> Changed consensus to manual-seal

Cargo.lock, README.md, node/Cargo.toml, runtime/Cargo.toml
I'm thinking that we can do the `1.0.0` release after https://github.com/paritytech/substrate/issues/10301 has been closed.
=> Sync with Substrate + Release 0.11.0

README.md, node/src/command.rs
Closes https://github.com/paritytech/substrate-contracts-node/issues/54 and https://github.com/paritytech/substrate-contracts-node/issues/51.
[Preview here](https://github.com/paritytech/substrate-contracts-node/tree/cmichi-make-dev-default#substrate-contracts-node).
=> Make `--dev` default behavior and highlight modifications that have been made for non-production use

.gitlab-ci.yml
Fixes #47 
We can build for both architectures on an Intel machine and then create an universal binary from it. No need to have separate downloads for each architecture. I created a dummy tag in order to test it.
=> Create universal binary for mac (Intel + Arm)

.github/dependabot.yml
Recently Dependabot has been spamming this repo trying to update Substrate related
crates. We manually update Substrate and friends anyways, so this is unnecessary.
=> Prevent Dependabot from updating Substrate related crates

Cargo.lock, Cargo.toml, README.md, node/src/command.rs, runtime/src/lib.rs
- Sync with substrate
- Use new resolver
- Add support for https://github.com/paritytech/substrate/pull/11819
- Make `--dev` the default
- Add sane log filtering (reduce block production noise and print contracts debug buffer by default)
=> Various improvements + Sync with substrate

Cargo.lock, README.md, node/Cargo.toml, runtime/Cargo.toml
Let's stop tracking Substrate master and use Polkadot release branches instead. This will help us getting https://github.com/paritytech/substrate-contracts-node/pull/146 merged.
This will also resolve the build problems we are seeing where `--locked` is broken. In fact, we don't need locked anymore.
Fixes https://github.com/paritytech/substrate-contracts-node/issues/78 https://github.com/paritytech/substrate-contracts-node/issues/121 https://github.com/paritytech/substrate-contracts-node/issues/151 https://github.com/paritytech/substrate-contracts-node/issues/150 https://github.com/paritytech/substrate-contracts-node/issues/9
=> Track polkadot release branch

Cargo.lock, node/src/chain_spec.rs, runtime/Cargo.toml, runtime/src/lib.rs
Added support of the [chain extension](https://github.com/Supercolony-net/pallet-assets-chain-extension) for `pallet-assets`. The extension requires additional changes on the `pallet-assets` side to be ready for production. But we ca enable it already for testing=)
=> Added support of `pallet-assets` and chain extension for it.

Cargo.lock, README.md, node/Cargo.toml, node/src/benchmarking.rs, node/src/cli.rs, node/src/command.rs, node/src/rpc.rs, node/src/service.rs, runtime/Cargo.toml, runtime/src/lib.rs
Most notable is the change to WeightsV2. This will break all off chain tooling.
I also removed support for `runtime-benchmarks` and `try-runtime`:
- Those were already broken because those features were not exercised in the CI
- You would not run those on a dev node but rather on an actual runtime
Let's merge this but wait with an release for the new polkadot branch on wednesday so we get the stable functions needed for ink!4.
=> Update to `polkadot-v0.9.31`

.gitlab-ci.yml
PR changes ci runners for dynamically created ones
cc https://github.com/paritytech/ci_cd/issues/730
=> [ci] Change runners

README.md
This flag got removed from Substrate a while ago.
Related issue: https://github.com/paritytech/ink/issues/1007
=> Remove `--tmp` flag from instructions

.gitlab-ci.yml, Cargo.lock, README.md, node/Cargo.toml, node/src/rpc.rs, node/src/service.rs, runtime/Cargo.toml, runtime/src/lib.rs
This PR syncs with the [`polkadot-v0.9.42`](https://github.com/paritytech/substrate/tree/polkadot-v0.9.42) branch.
=> Sync with polkadot-v0.9.42 branch

.gitlab-ci.yml, runtime/src/lib.rs
This is needed in order to make the e2e test for [call_runtime](https://github.com/paritytech/ink/blob/e267dd15730c3d19d5030fa440292f849acf9960/integration-tests/call-runtime/lib.rs#L150) pass
=> CallFilter: allow call to Balances' `transfer_allow_death()`

.gitlab-ci.yml, runtime/src/lib.rs
In recent PR https://github.com/paritytech/substrate-contracts-node/pull/182#issuecomment-1536514910, the CI step of running `cargo test` was commented out as a dirty workaround for the pallet contracts integrity test failure. The test checks that the pallet configuration is memory safe.
So to make the test pass, we enlarge the runtime memory limit in the Schedule. We do this because this development node [allows](https://github.com/paritytech/substrate-contracts-node/blob/8d13ddef3f5c728d1661e79c511a28cef206b298/runtime/src/lib.rs#L367) larger contract size than it is normally allowed in a production running node. This should be fine for the development node where possible security implications could be neglected for the sake of development convenience. **However, please DO NOT do this …
=> Customize schedule with runtime memory limit suitable for development node

Cargo.lock, node/Cargo.toml, runtime/Cargo.toml
#180 upgraded to [polkadot-v0.9.42](https://github.com/paritytech/substrate/tree/polkadot-v0.9.42).
This PR bumps the version to `0.26.0` in preparation for a release tag.
=> Release `v0.26.0`

Cargo.lock, node/Cargo.toml, runtime/Cargo.toml
Updates lockfile to point to `polkadot-1.0.0` HEAD, to include the enabling of `sign_ext`
=> Release `v0.29.0`

Cargo.lock, node/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
Use all substrate/polkadot-sdk dependencies from crates.io, remove `pallet-asset-chain-extension` so we can release this to crates.io. See #203
=> Use crates.io dependencies, remove chain extension

Cargo.lock, README.md, node/Cargo.toml, runtime/Cargo.toml
Closes #203. This will be the first release to crates.io:
- Use crates.io dependencies, remove chain extension #204
=> Release `v0.31.0`

Cargo.lock, runtime/Cargo.toml, runtime/src/lib.rs
It has been reported an issue (https://github.com/paritytech/ink/issues/1985) that weight_to_fee always returns zero in end-to-end tests. 
This pull request adds `type FeeMultiplierUpdate = SlowAdjustingFeeUpdate<Self>` to make it work.
=> Make weight_to_fee work in the solo chain

README.md, node/src/cli.rs, node/src/command.rs, node/src/service/dev.rs
Adds `--finalize-delay-sec` cli argument, based on the great work by @shunsukew at https://github.com/inkdevhub/swanky-node/pull/61.
Manual testing by starting node with/without option, along with example contract upload:
```shell
cargo contract build --manifest-path=../ink-examples/erc20/Cargo.toml
cargo run
cargo contract upload --suri //Alice --execute --manifest-path=../ink-examples/erc20/Cargo.toml
sleep 1
test $(curl -sH "Content-Type: application/json" -d '{"id":"1", "jsonrpc":"2.0", "method": "chainHead_unstable_genesisHash", "params":[]}' http://localhost:9944 | jq .result) \
= $(curl -sH "Content-Type: application/json" -d '{"id":"1", "jsonrpc":"2.0", "method": "chain_getFinalizedHead", "params":[]}' http://localhost:9944 | jq .result) && echo PASS || echo FAIL
cargo run -- …
```
=> feat: delayed finalization

Cargo.lock, Cargo.toml, node/Cargo.toml
To fix `ink!` CI with https://github.com/paritytech/substrate-contracts-node/pull/224
=> Release `0.38.0`
